### ISSUE TITLE
PHP hanging indefinitely due to stream_get_contents

### ISSUE THREAD

**Issue by sevn** [kbjr/Git.php#57]
Reading from stream_get_contents on a stream that never gets output will hang PHP indefinitely. This is caused typically when output gets sent to STDERR instead of STDOUT.

In the case of Git commands this is happening to me on initial commit (git add .) when Git replaces LF with CRLF.

> warning: LF will be replaced by CRLF in example.txt.
> The file will have its original line endings in your working directory.

Unfortunately there is no current solution to this problem from the research I've read except to output to files via the shell command. More can be extensively read here where these folk have the same problem.

https://github.com/mikehaertl/php-shellcommand/issues/20

For now I've turned off the warning I'm getting from Git with this config setting
`git config core.safecrlf false`

**Comment by kbjr** [comment]
Have you seen this: http://php.net/manual/en/function.proc-open.php#97012 ?

**Comment by sevn** [comment]
No, I havn't. Good catch. I'll try that when I get some time and make a PR later.
