### ISSUE TITLE
Git Pull/Push error

### ISSUE THREAD

**Issue by roshan2806** [kbjr/Git.php#61]
Hi, 
I am just used your library for integrating git with php framework.
So i have one repo with ssh supports need to pull or push command from php itself.
But when i used command from linux framework it throws error as below, 

Message: Could not create directory '/home/ampps/.ssh'.
Host key verification failed.
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.

Here 'ampps' is my apache user.

Can you please help me out?
Thank you.

**Comment by kbjr** [comment]
Well, the error is saying you don't have permissions because it tried to read an SSH key from `/home/ampps/.ssh` which doesn't appear to exist, and your user also appears to not have permissions to create it.

If you need to use git over ssh, you need to set up your user with valid ssh credentials.
